'use client'
import '../../public/main.scss'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "../redux/providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main-page-wrapper flex min-w-[100%] items-center justify-center p0">
          <Providers>{children}</Providers>
        </div>       
      </body>
    </html>
  )
}
